e_diary_attendancies:
    resource: "@EDiaryBundle/Controller/AttendanciesController.php"
    type:     annotation

e_diary_lessons:
    resource: "@EDiaryBundle/Controller/LessonsController.php"
    type:     annotation

e_diary_courses:
    resource: "@EDiaryBundle/Controller/CoursesController.php"
    type:     annotation

e_diary_pages:
    resource: "@EDiaryBundle/Controller/PagesController.php"
    type:     annotation

e_diary_users:
    resource: "@EDiaryBundle/Controller/UsersController.php"
    type:     annotation

e_diary:
    resource: "@EDiaryBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"